version: '2'
networks: 
  weiqi_dev: 
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.110.0/24
services: 
  weiqi_core:
    image: u03013112/weiqi_core:v1
    container_name: 'weiqi_core'
    tty: true
    volumes:
        - ../core:/core:cached
        - ../log:/log:cached
    working_dir: /core/
    # network_mode: host
    ports:
      - 0.0.0.0:8088:8080
    networks:
      - weiqi_dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
  
  weiqi_nginx:
    image: nginx:alpine
    container_name: 'nginx-port82'
    tty: true
    volumes:
        - ../ui/www:/www
        - ../ui/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 82:80
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
  
  weiqi_ai:
    image: tensorflow/tensorflow:latest
    container_name: 'weiqi_ai'
    tty: true
    volumes:
        - ../ai:/ai:cached
        - ../log:/log:cached
    working_dir: /ai/
    networks:
      - weiqi_dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
  